name: Download Docker Image

on:
  workflow_dispatch:

jobs:
  download-mysql:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Pull Docker image
      run: docker pull mysql

    - name: Save Docker image to file
      run: docker save mysql -o ./mysql.tar

    - name: List files in the repository
      run: ls -la
      
    # - name: Create example.txt file
    #   run: echo "This is an example file." > example.txt

    # - name: Commit and push txt file
    #   run: |
    #     git config --global user.email "170225345@qq.com"
    #     git config --global user.name "jie-fu170"
    #     git add example.txt
    #     git commit -m "Add example.txt file"
    #     git push
    # - name: Install Git LFS
    #   run: |
    #     sudo apt-get update
    #     sudo apt-get install git-lfs
    #     git lfs install

    # - name: Track tar files using Git LFS
    #   run: |
    #     git lfs track "*.tar"
    #     git add .gitattributes
    #     git commit -m "Add Git LFS tracking for tar files" || echo "No changes to .gitattributes"

    - name: Upload file to Dropbox
      run: |
        curl -X POST https://content.dropboxapi.com/2/files/upload \
        --header "Authorization: Bearer ${{ secrets.DROPBOX_ACCESS_TOKEN }}" \
        --header "Dropbox-API-Arg: {\"path\": \"/mysql.tar\",\"mode\": \"add\",\"autorename\": true,\"mute\": false}" \
        --header "Content-Type: application/octet-stream" \
        --data-binary @mysql.tar
        
    # - name: Commit and push tar file
    #   run: |
    #     git config --global user.email "170225345@qq.com"
    #     git config --global user.name "jie-fu170"
    #     git add ./alpine.tar
    #     git commit -m "Add Docker image tar file"
    #     # git config lfs.https://github.com/Jie-Fu170/GithubActionSample.git/info/lfs.locksverify false
    #     # git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/Jie-Fu170/GithubActionSample.git
    #     # git push origin main
    #     git push
      env:
        PAT: ${{ secrets.PAT }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
