name: Download MySQL Docker Image

on:
  workflow_dispatch:

jobs:
  download-mysql:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Pull MySQL Docker image
      run: docker pull mysql:latest

    - name: Save Docker image to file
      run: docker save mysql:latest -o ./mysql_latest.tar

    - name: List files in the repository
      run: ls -la
      
    - name: Commit and push tar file
      run: |
        git config --global user.email "170225345@qq.com"
        git config --global user.name "jie-fu170"
        git add ./mysql_latest.tar
        git commit -m "Add MySQL Docker image tar file"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
